name: nba_prediction_app
description: NBA比赛预测系统移动应用

# 应用版本信息
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  fl_chart: ^0.62.0
  intl: ^0.18.0
  sqflite: ^2.2.8
  path_provider: ^2.0.14
  flutter_local_notifications: ^13.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
